server:
  port: 8010

spring:
  application:
    name: nacos-provider

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.105:8847,192.168.1.105:8848,192.168.1.105:8849
        namespace: 1be86fed-e1b1-4144-9d49-c0bc8416c772
        watch-delay: 3000
        metadata:
          - name: nacos-provider
          - port: 8010
          - group: none



provider:
  name: glamey(dev)
  address: daxing,beijing