spring:
  application:
    name: eureka-server
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  # eureka server相关配置
  server:
    #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上,默认30s
    response-cache-update-interval-ms: 3000
    ##eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，过期后从registry重新读取注册服务信息，
    #registry是一个ConcurrentHashMap。由于启用了evict其实就用不太上改这个配置了，默认180S
    response-cache-auto-expiration-in-seconds: 180
    #启用主动失效，并且每次主动失效检测间隔为3s，默认60S
    eviction-interval-timer-in-ms: 3000
    # 其实我们可以禁用readOnlyMap的操作
    #use-read-only-response-cache: false


