server:
  port: 9010

spring:
  application:
    name: nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.210.164:8847,192.168.210.164:8848,192.168.210.164:8849
    loadbalancer:
      retry:
        enabled: false


