server:
  port: 9010

spring:
  application:
    name: nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.210.164:8847,192.168.210.164:8848,192.168.210.164:8849
    loadbalancer:
      retry:
        enabled: false


#  注意：https://github.com/alibaba/nacos/issues/452#issuecomment-501620432 具体原因看我写的wiki回复
#  main:
#    allow-bean-definition-overriding: false


